### PR TITLE
#54 Automatic-Module-Name

### PR DESCRIPTION
**Pull request by nhojpatrick**
This is the pattern I've used with other projects like hamcrest and cucumber to start the ball rolling.
I'm currently working on getting cucumber closer to a full jpms build so if 0.6.2 could be released asap once this is merged that would be really useful as it's one of the last dependencies that needed fixing.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Build is failing because OracleJDK 8 is no longer available in package managers. You'd have to either bump the version or stick with OpenJDK8.

**Comment by mpkorstanje** [comment]
@jhalterman is anything we can help you with to get this merged?

**Comment by nhojpatrick** [comment]
@jhalterman anything I can help with to get this pr approved, merged and released?

@mpkorstanje if this doesn't get released in a few months shall we to a temp release under the io.cucumber groupId? So that I can progress with a full Java Module version of Cucumber...

**Comment by jhalterman** [comment]
Apologies for the delay. Will cut a release shortly.

**Comment by jhalterman** [comment]
This is released in 0.6.2.

**Comment by nhojpatrick** [comment]
> This is released in 0.6.2.

Cheers, already testing.

Next steps, Java module-info, i'll prepare a branch and we can table about that next...

**Pull request merged**
