### PR TITLE
Fix lambda inference on openj9 VM

### PR DESCRIPTION
**Pull request by Nuclearfarts**
Currently, lambda generic inference (not really sure what to call it) fails on the OpenJ9 VM since `Class.getConstantPool()` does not exist. This PR switches to using `JavaLangAccess.getConstantPool(Class)`, which exists on both OpenJ9 and the standard Hotspot VM, and an instance of it can be acquired via `sun.misc.SharedSecrets` on Java 8 and lower or `jdk.internal.misc.SharedSecrets` on Java 9 and higher, both of which exist on both OpenJ9 and Hotspot.

### CODE REVIEW

**Comment by jhalterman** [comment]
Seems this builds poorly locally.

**Comment by jhalterman** [comment]
Apologies - I merged this one without realizing it caused test failures locally (though CI passed). Could you have a look again and possibly submit another PR? It's worth noting a previous, similar PR was submitted in #49 which might be a useful reference.

**Comment by Nuclearfarts** [comment]
Ah, I see the comments on #49 mention that `SharedSecrets` moved again in JDK 12. I only tested on JDK 8 and JDK 11.

**Comment by jhalterman** [comment]
I'm actually running on JDK 8 locally FWIW - I think the test failures may have to do with some of the other PRs that just merged before this (but haven't had a chance to look closely).

**Comment by Nuclearfarts** [comment]
Tests are all passing locally for me, on both JDK 8 and JDK 11, both HotSpot and OpenJ9. A quick check of JDK 13 showed that `AccessibleObject.override` is now in the reflection blacklist, so it crashes there anyway.

**Comment by jhalterman** [comment]
Were you testing with this commit rebased onto the current master?

**Pull request merged**
