### PR TITLE
Patch candidate for OSGi support

### PR DESCRIPTION
**Pull request by pderop**
I changed the pom.xml in order to generate an OSGi bundle, using maven-bundle-plugin.

Also, while doing a real test under Felix, I realized that it was not working. I figured out that the TypeResolver class was doing a class.forName in order to load actual type classes, but we can't do this within an OSGi environment, and the bundle classloader has to be used.
So, I added a patch in TypeDescriptor.java, in order to use the bundle classloader of the lambda expression. It seems to work. 

Please review, thanks.

PS: first time I'm using github ... hope my pull request is correct ...

### CODE REVIEW

**Comment by jhalterman** [comment]
This looks pretty good to me. I'm not an OSGI user so I can't verify that the bundle works - but I assume it does? :)

**Comment by kuujo** [comment]
Awesome! Welcome to GitHub!

**Comment by pderop** [comment]
Yes Jonathan, it works, I tested with Felix 4.6.1.

Now, ultimately, it would be nice to see if we can add an integration test
in your pom, using pax-exam, in order to execute some tests under Osgi ...
I will see if I can do this (but I'm affraid I won't have time to do this
quickly).

Once remark: the TypeTools OSGi manifest is importing the package
"sun.reflect" ("Import-Package: sun.reflect" in the OSGi manifest headers).

So, I think that in your documentation, you should mention that and say
that the OSGi framework should "reexport" the "sun.reflect" package to the
"system bundles", like the following using Felix:

org.osgi.framework.system.packages.extra=sun.reflect

So, I suggest to document:

---
OSGi support: When using TypeTools in an OSGi environment, the
"sun.reflect" system package should be exported by the framework to the
application bundles, because TypeTools is importing it.

For example, in Felix, configure the following in the config.properties
file:

   org.osgi.framework.system.packages.extra=sun.reflect
---


/Pierre

**Comment by jhalterman** [comment]
Looks good. I don't think an integration test is necessary. Thanks for this!

**Comment by jhalterman** [comment]
0.4.1 has been released. It should be in central shortly..

**Pull request merged**
